version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    hostname: db_container
    networks:
      - gateway
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=predictor
      - POSTGRES_PASSWORD=predictor
      - POSTGRES_DB=predictor
  predictors:
    image: 5ginfire_predictors
    hostname: predictors_container
    networks:
      - gateway
    ports:
      - 8000:8000
    depends_on:
      - db
  metric_collector:
    image: 5ginfire_metric_collector
    hostname: metrics_container
    networks:
      - gateway
    depends_on:
      - predictors

volumes:
  postgres_data:

networks:
  gateway:
  #local:
  #name: gateway
